import { computed, ref } from 'vue'
import { vi } from 'vitest'
import type { AccumulatedPermission } from '@/entity/structure'

export function createDialogState() {
  return {
    isLoading: ref(true),
    form: ref<Record<string, unknown>>({ title: '' }),
    formRef: ref(null),
    activeTab: ref(0),
    selectedRelations: ref({}),
    visibleTemplates: computed(() => [{ name: 'title', type: 'string' }]),
    visibleTemplateGroups: computed(() => [{ id: 'main', label: '', templates: [] }]),
    relationTemplates: computed(() => []),
    dirtyRelationNames: computed<string[]>(() => []),
    relationTableHeaders: ref({}),
    relationTableState: ref({}),
    relationTableItems: ref({}),
    relationTableSearch: ref({}),
    relationTablePage: ref({}),
    relationTableTotal: ref({}),
    relationTableItemsPerPage: ref({}),
    relationTableSortBy: ref({}),
    relationTableColumnFilters: ref({}),
    permissions: ref<AccumulatedPermission[]>([]),
    iconNames: ref([]),
    selectedItems: ref([]),
    isDirty: computed(() => false),
    canSubmit: computed(() => false),
    isSaving: computed(() => false),
    unsavedChangesDialog: ref(false),
    pendingSaveAction: ref(null),
    validationFeedback: ref<{
      action: 'save' | 'saveAndClose'
      attempt: number
    } | null>(null),
    dirtyFieldCount: computed(() => 0),
    formConfigMenuItems: computed(() => []),
    selectedFormConfigLabel: computed(() => ''),
    selectFormConfig: vi.fn(),
    getRules: vi.fn().mockReturnValue([]),
    getTemplateColumnProps: vi.fn().mockReturnValue({ cols: 12 }),
    isTemplateDirty: vi.fn().mockReturnValue(false),
    getDirtyTemplateCount: vi.fn().mockReturnValue(0),
    isFieldDisabled: vi.fn().mockReturnValue(false),
    isReferenceFieldDisabled: vi.fn().mockReturnValue(false),
    getReferenceParentFilter: vi.fn(),
    handleDialogUpdate: vi.fn(),
    onDuplicateSelect: vi.fn(),
    cancel: vi.fn(),
    keepEditing: vi.fn(),
    discardChanges: vi.fn(),
    saveChangesAndClose: vi.fn(),
    resetForm: vi.fn(),
    save: vi.fn(),
    saveAndClose: vi.fn(),
    addRelation: vi.fn(),
    stageNewRelationRecord: vi.fn(),
    removeRelation: vi.fn(),
    onRelationTablePage: vi.fn(),
    onRelationTableItemsPerPage: vi.fn(),
    onRelationTableSort: vi.fn(),
    onRelationTableColumnFilters: vi.fn(),
    onRelationTableReload: vi.fn(),
  }
}
