export const VECTOR_ENTITY_HANDLES = [
  'ticket',
  'event',
  'salesOpportunity',
  'effortEstimate',
  'effortEstimatePosition',
  'knowledgeArticle',
] as const;

export type VectorizableEntityHandle = (typeof VECTOR_ENTITY_HANDLES)[number];

export const VECTOR_SEARCHABLE_SECTIONS: Record<
  VectorizableEntityHandle,
  string[]
> = {
  ticket: ['overview', 'problem', 'solution'],
  event: ['overview', 'description'],
  salesOpportunity: ['overview', 'description', 'painPoints'],
  effortEstimate: ['overview', 'requirements'],
  effortEstimatePosition: ['overview', 'offerText'],
  knowledgeArticle: ['overview', 'problem', 'solution', 'documentation'],
};

export const VECTOR_SECTION_FIELD_PATHS: Record<
  VectorizableEntityHandle,
  Record<string, string[]>
> = {
  ticket: {
    overview: [
      'handle',
      'number',
      'externalNumber',
      'title',
      'status.description',
      'priority.description',
      'creatorCompany.name',
      'creatorPerson.firstName',
      'creatorPerson.lastName',
      'creatorPerson.email',
      'assigneeCompany.name',
      'assigneePerson.firstName',
      'assigneePerson.lastName',
      'assigneePerson.email',
      'problemDescription',
      'solutionDescription',
    ],
    problem: [
      'handle',
      'number',
      'externalNumber',
      'title',
      'status.description',
      'priority.description',
      'creatorCompany.name',
      'creatorPerson.firstName',
      'creatorPerson.lastName',
      'creatorPerson.email',
      'assigneeCompany.name',
      'assigneePerson.firstName',
      'assigneePerson.lastName',
      'assigneePerson.email',
      'problemDescription',
    ],
    solution: [
      'handle',
      'number',
      'externalNumber',
      'title',
      'status.description',
      'priority.description',
      'creatorCompany.name',
      'creatorPerson.firstName',
      'creatorPerson.lastName',
      'creatorPerson.email',
      'assigneeCompany.name',
      'assigneePerson.firstName',
      'assigneePerson.lastName',
      'assigneePerson.email',
      'solutionDescription',
    ],
  },
  event: {
    overview: [
      'handle',
      'title',
      'status.description',
      'type.description',
      'category.title',
      'startDate',
      'endDate',
      'creatorCompany.name',
      'creatorPerson.firstName',
      'creatorPerson.lastName',
      'creatorPerson.email',
      'assigneeCompany.name',
      'assigneePerson.firstName',
      'assigneePerson.lastName',
      'assigneePerson.email',
      'ticket.number',
      'ticket.title',
      'salesOpportunity.title',
      'description',
    ],
    description: [
      'handle',
      'title',
      'status.description',
      'type.description',
      'category.title',
      'startDate',
      'endDate',
      'creatorCompany.name',
      'creatorPerson.firstName',
      'creatorPerson.lastName',
      'creatorPerson.email',
      'assigneeCompany.name',
      'assigneePerson.firstName',
      'assigneePerson.lastName',
      'assigneePerson.email',
      'ticket.number',
      'ticket.title',
      'salesOpportunity.title',
      'description',
    ],
  },
  salesOpportunity: {
    overview: [
      'handle',
      'title',
      'type.description',
      'forecast.description',
      'source.description',
      'expectedRevenue',
      'probability',
      'closeDate',
      'nextStep',
      'creatorCompany.name',
      'creatorPerson.firstName',
      'creatorPerson.lastName',
      'creatorPerson.email',
      'assigneeCompany.name',
      'assigneePerson.firstName',
      'assigneePerson.lastName',
      'assigneePerson.email',
      'description',
      'painPoints',
    ],
    description: [
      'handle',
      'title',
      'type.description',
      'forecast.description',
      'source.description',
      'expectedRevenue',
      'probability',
      'closeDate',
      'nextStep',
      'creatorCompany.name',
      'creatorPerson.firstName',
      'creatorPerson.lastName',
      'creatorPerson.email',
      'assigneeCompany.name',
      'assigneePerson.firstName',
      'assigneePerson.lastName',
      'assigneePerson.email',
      'description',
    ],
    painPoints: [
      'handle',
      'title',
      'type.description',
      'forecast.description',
      'source.description',
      'expectedRevenue',
      'probability',
      'closeDate',
      'nextStep',
      'creatorCompany.name',
      'creatorPerson.firstName',
      'creatorPerson.lastName',
      'creatorPerson.email',
      'assigneeCompany.name',
      'assigneePerson.firstName',
      'assigneePerson.lastName',
      'assigneePerson.email',
      'painPoints',
    ],
  },
  effortEstimate: {
    overview: [
      'handle',
      'title',
      'status.description',
      'expectedCompletionDate',
      'creatorCompany.name',
      'creatorPerson.firstName',
      'creatorPerson.lastName',
      'creatorPerson.email',
      'assigneeCompany.name',
      'assigneePerson.firstName',
      'assigneePerson.lastName',
      'assigneePerson.email',
      'ticket.number',
      'ticket.title',
      'salesOpportunity.title',
      'requirementsMarkdown',
    ],
    requirements: [
      'handle',
      'title',
      'status.description',
      'expectedCompletionDate',
      'creatorCompany.name',
      'creatorPerson.firstName',
      'creatorPerson.lastName',
      'creatorPerson.email',
      'assigneeCompany.name',
      'assigneePerson.firstName',
      'assigneePerson.lastName',
      'assigneePerson.email',
      'ticket.number',
      'ticket.title',
      'salesOpportunity.title',
      'requirementsMarkdown',
    ],
  },
  effortEstimatePosition: {
    overview: [
      'handle',
      'title',
      'estimatedHours',
      'isOptional',
      'estimate.title',
      'template.title',
      'offerTextMarkdown',
    ],
    offerText: [
      'handle',
      'title',
      'estimatedHours',
      'isOptional',
      'estimate.title',
      'template.title',
      'offerTextMarkdown',
    ],
  },
  knowledgeArticle: {
    overview: [
      'handle',
      'title',
      'status.description',
      'visibility.description',
      'category.title',
      'product.title',
      'contextKey',
      'tags',
      'publishedAt',
      'validUntil',
      'sourceTicket.number',
      'sourceTicket.title',
      'sourceSalesOpportunity.title',
      'sourceEffortEstimate.title',
      'authorPerson.firstName',
      'authorPerson.lastName',
      'authorPerson.email',
      'reviewerPerson.firstName',
      'reviewerPerson.lastName',
      'reviewerPerson.email',
      'summary',
      'problemMarkdown',
      'solutionMarkdown',
      'documentationMarkdown',
    ],
    problem: [
      'handle',
      'title',
      'status.description',
      'visibility.description',
      'category.title',
      'product.title',
      'contextKey',
      'tags',
      'publishedAt',
      'validUntil',
      'sourceTicket.number',
      'sourceTicket.title',
      'sourceSalesOpportunity.title',
      'sourceEffortEstimate.title',
      'authorPerson.firstName',
      'authorPerson.lastName',
      'authorPerson.email',
      'reviewerPerson.firstName',
      'reviewerPerson.lastName',
      'reviewerPerson.email',
      'problemMarkdown',
    ],
    solution: [
      'handle',
      'title',
      'status.description',
      'visibility.description',
      'category.title',
      'product.title',
      'contextKey',
      'tags',
      'publishedAt',
      'validUntil',
      'sourceTicket.number',
      'sourceTicket.title',
      'sourceSalesOpportunity.title',
      'sourceEffortEstimate.title',
      'authorPerson.firstName',
      'authorPerson.lastName',
      'authorPerson.email',
      'reviewerPerson.firstName',
      'reviewerPerson.lastName',
      'reviewerPerson.email',
      'solutionMarkdown',
    ],
    documentation: [
      'handle',
      'title',
      'status.description',
      'visibility.description',
      'category.title',
      'product.title',
      'contextKey',
      'tags',
      'publishedAt',
      'validUntil',
      'sourceTicket.number',
      'sourceTicket.title',
      'sourceSalesOpportunity.title',
      'sourceEffortEstimate.title',
      'authorPerson.firstName',
      'authorPerson.lastName',
      'authorPerson.email',
      'reviewerPerson.firstName',
      'reviewerPerson.lastName',
      'reviewerPerson.email',
      'documentationMarkdown',
    ],
  },
};

export const VECTOR_SEARCH_RELATIONS: Record<
  VectorizableEntityHandle,
  string[]
> = {
  ticket: [
    'status',
    'priority',
    'creatorCompany',
    'creatorPerson',
    'assigneeCompany',
    'assigneePerson',
  ],
  event: [
    'status',
    'type',
    'category',
    'creatorCompany',
    'creatorPerson',
    'assigneeCompany',
    'assigneePerson',
    'ticket',
    'salesOpportunity',
    'participants',
  ],
  salesOpportunity: [
    'type',
    'forecast',
    'source',
    'creatorCompany',
    'creatorPerson',
    'assigneeCompany',
    'assigneePerson',
  ],
  effortEstimate: [
    'status',
    'creatorCompany',
    'creatorPerson',
    'assigneeCompany',
    'assigneePerson',
    'ticket',
    'salesOpportunity',
  ],
  effortEstimatePosition: ['estimate', 'estimate.status', 'template'],
  knowledgeArticle: [
    'status',
    'visibility',
    'category',
    'product',
    'sourceTicket',
    'sourceSalesOpportunity',
    'sourceEffortEstimate',
    'authorPerson',
    'reviewerPerson',
  ],
};

export const VECTOR_SEARCH_USAGE_HINTS: Record<
  VectorizableEntityHandle,
  string[]
> = {
  ticket: [
    'Use semantic search for natural-language problem descriptions, symptoms, and workaround requests.',
    'Use ticket_search for exact ticket numbers, strict keywords, or external references.',
  ],
  event: [
    'Use semantic search for natural-language event descriptions, meeting context, and agenda-like text.',
  ],
  salesOpportunity: [
    'Use semantic search for sales opportunity descriptions, customer pain points, and qualification context.',
  ],
  effortEstimate: [
    'Use semantic search for requirement texts, scope descriptions, and expected implementation outcomes.',
  ],
  effortEstimatePosition: [
    'Use semantic search for offer text, implementation tasks, and estimate position scope.',
  ],
  knowledgeArticle: [
    'Use semantic search for curated knowledge-base articles, reusable fixes, procedures, estimation guidance, and sales enablement notes.',
  ],
};
